name: Push & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy With Latest Code
        uses: appleboy/ssh-action@master
        with:
          host: '143.198.233.236' # IP address of the server you wish to ssh into
          username: 'root' # User of the server you want to ssh into
          password: 'odoo15!' # SSH server user password
          port: '22' # SSH server port
          script_stop: true # Will stop build incase of any failures
          script: |
            cd /home/root/odoo
            git pull origin main
            docker build -t odoo:15.0 .
            docker-compose down
            docker-compose up -d
            docker system prune -f
